# Generated by Django 5.0.6 on 2024-06-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersBD',
        ),
    ]
