# Generated by Django 5.0.6 on 2024-06-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_users_usersbd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersBD',
            new_name='Accounts',
        ),
    ]
