# Generated by Django 5.0.6 on 2024-06-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_usersbd_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
