# Generated by Django 5.0.6 on 2024-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_accounts_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
